### ISSUE TITLE
Feature Request: Support for using heroku postgres outside of heroku

### ISSUE THREAD

**Issue by davidmc24** [login-box/dropwizard-heroku#32]
Heroku allows external access to its postgres databases, but only over SSL.  This can be useful for testing an application destined for Heroku locally.

https://devcenter.heroku.com/articles/connecting-to-relational-databases-on-heroku-with-java#connecting-to-a-database-remotely

**Comment by ojacobson** [comment]
Huh. It wouldn't have occurred to me to use a Heroku database to develop locally: I use [Postgres.app](http://postgresapp.com/) to run a development database, instead, for example. I'll patch something in to make this work; do you have opinions about the user interface side of this?

I don't like Heroku's recommended approach, much: "fuck it, turn off certificate validation" is a terrible way to deal with validation issues. I do have some insight into why those validation issues exist, so I can't really fault them on that front, but I'm going to pressure Heroku to use [Let's Encrypt](https://letsencrypt.org/) for ephemeral services as soon as that's live and widely-respected. In the interim I don't think it's suitable to default to SSL _when running on Heroku_, since broken SSL is in some ways worse than no SSL.

Do you think it'd be sufficient to copy query parameters from `DATABASE_URL` into the generated JDBC URL? Local development would have to use 

    DATABASE_URL=postgres://mumble@some-random-ec2-host/my-database?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory

**Comment by davidmc24** [comment]
Thanks for the quick respo

**Comment by davidmc24** [comment]
Gah, phone interface. Thanks for the quick response. I think your proposal of supporting use of query parameters in the env var URL is a great way to go. It facilitates the use case cleanly without adding any surprising "magical" behaviors (such as always skipping certificate validation).

**Comment by ojacobson** [comment]
If you want to give this a try, there's a snapshot release available. Add the repo `https://dl.bintray.com/login-box/snapshots/` to your repositories and set the desired version to ` 0.1.3-dev.1+7885623 `. If that solves your issue, let me know and I'll release it (probably as version `0.2.0`).

**Comment by davidmc24** [comment]
@ojacobson Works great!  Thank you for being so responsive.  This project makes using dropwizard with Heroku so much easier.

**Comment by ojacobson** [comment]
Sorry it took me so long to get to the release! It's out on Bintray now, as version `0.2.0`. Enjoy!
